server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EiLunge/git-springcloudConfig #github上面的git仓库名字
          search-paths:
            - git-springcloudConfig
          strict-host-key-checking: false #解决https问题
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka